=== JIIIIIND/Learning-outcomes/프로그래밍 언어/과제 3(XML 프로그래밍)/xLang2018스키마와예제/xLang2018.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by Lee (CNU) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="xLang18">
		<xs:annotation>
			<xs:documentation>XML-based Language</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Author" type="xs:string"/>
				<xs:element name="Function" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Fname" type="xs:string"/>
							<xs:element name="Param" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Vname" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Statement" type="stmtType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="stmtType">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Assign">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Vname" type="xs:string"/>
						<xs:group ref="exprGroup"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="If">
				<xs:complexType>
					<xs:sequence>
						<xs:group ref="condGroup"/>
						<xs:element name="Then" type="stmtType"/>
						<xs:element name="Else" type="stmtType" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="While">
				<xs:complexType>
					<xs:sequence>
						<xs:group ref="condGroup"/>
						<xs:element name="Do" type="stmtType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Input">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Vname" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Output">
				<xs:complexType>
					<xs:sequence>
						<xs:group ref="exprGroup"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Return">
				<xs:complexType>
					<xs:sequence>
						<xs:group ref="exprGroup"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:group name="exprGroup">
		<xs:choice>
			<xs:element name="Add">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Sub">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Mul">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Div">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Mod">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Vname" type="xs:string"/>
			<xs:element name="Num" type="xs:string"/>
			<xs:element name="Fun">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Fname" type="xs:string"/>
						<xs:element name="Param" minOccurs="0">
							<xs:complexType>
								<xs:group ref="exprGroup" maxOccurs="unbounded"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="condGroup">
		<xs:choice>
			<xs:element name="EQ">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="NE">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="GE">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="GT">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="LE">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="LT">
				<xs:complexType>
					<xs:group ref="exprGroup" minOccurs="2" maxOccurs="2"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
</xs:schema>

=== JIIIIIND/Learning-outcomes/프로그래밍 언어/과제 3(XML 프로그래밍)/xLangTools2018/xLangExample2018.xml
<?xml version="1.0" encoding="UTF-8"?>
<xLang18 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xLang2018.xsd">
	<Author>Su-Hyun Lee</Author>
	<Function>
		<Fname>main</Fname>
		<Statement>
			<Assign>
				<Vname>a</Vname>
				<Num>1</Num>
			</Assign>
			<Assign>
				<Vname>sum</Vname>
				<Num>0</Num>
			</Assign>
			<Input>
				<Vname>n</Vname>
			</Input>
			<While>
				<LE>
					<Vname>a</Vname>
					<Vname>n</Vname>
				</LE>
				<Do>
					<Assign>
						<Vname>sum</Vname>
						<Add>
							<Vname>sum</Vname>
							<Vname>a</Vname>
						</Add>
					</Assign>
					<Assign>
						<Vname>a</Vname>
						<Add>
							<Vname>a</Vname>
							<Num>1</Num>
						</Add>
					</Assign>
				</Do>
			</While>
			<Output>
				<Vname>sum</Vname>
			</Output>
			<Return>
				<Num>0</Num>
			</Return>
		</Statement>
	</Function>
</xLang18>

=== JIIIIIND/Learning-outcomes/프로그래밍 언어/과제 3(XML 프로그래밍)/xLang2018스키마와예제/xLangPrimeNumber2018.xml
<?xml version="1.0" encoding="UTF-8"?>
<xLang18 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xLang2018.xsd">
	<Author>Su-Hyun Lee</Author>
	<Function>
		<Fname>main</Fname>
		<Statement>
			<Input>
				<Vname>n</Vname>
			</Input>
			<Return>
				<Fun>
					<Fname>recursive</Fname>
					<Param>
						<Vname>n</Vname>
					</Param>
				</Fun>
			</Return>
		</Statement>
	</Function>
	<Function>
		<Fname>recursive</Fname>
		<Param>
			<Vname>n</Vname>
		</Param>
		<Statement>
			<If>
				<EQ>
					<Vname>n</Vname>
					<Num>1</Num>
				</EQ>
				<Then>
					<Return>
						<Num>0</Num>
					</Return>
				</Then>
				<Else>
					<If>
						<EQ>
							<Fun>
								<Fname>prime</Fname>
								<Param>
									<Vname>n</Vname>
								</Param>
							</Fun>
							<Num>1</Num>
						</EQ>
						<Then>
							<Output>
								<Vname>n</Vname>
							</Output>
						</Then>
					</If>
					<Return>
						<Fun>
							<Fname>recursive</Fname>
							<Param>
								<Sub>
									<Vname>n</Vname>
									<Num>1</Num>
								</Sub>
							</Param>
						</Fun>
					</Return>
				</Else>
			</If>
		</Statement>
	</Function>
	<Function>
		<Fname>prime</Fname>
		<Param>
			<Vname>i</Vname>
		</Param>
		<Statement>
			<Assign>
				<Vname>p</Vname>
				<Num>1</Num>
			</Assign>
			<Assign>
				<Vname>j</Vname>
				<Num>2</Num>
			</Assign>
			<While>
				<LT>
					<Vname>j</Vname>
					<Vname>i</Vname>
				</LT>
				<Do>
					<If>
						<EQ>
							<Mod>
								<Vname>i</Vname>
								<Vname>j</Vname>
							</Mod>
							<Num>0</Num>
						</EQ>
						<Then>
							<Assign>
								<Vname>p</Vname>
								<Num>0</Num>
							</Assign>
						</Then>
					</If>
					<Assign>
						<Vname>j</Vname>
						<Add>
							<Vname>j</Vname>
							<Num>1</Num>
						</Add>
					</Assign>
				</Do>
			</While>
			<Return>
				<Vname>p</Vname>
			</Return>
		</Statement>
	</Function>
</xLang18>
